---
title: "02_cor_viz"
author: "Puvvula"
date: "2024-06-25"
output: pdf_document
---

#formatting
```{r}
cor_viz<- readRDS("~/Documents/methyl_concor/result/methyl_conc_results.rds") |>
  mutate(
    ucsc_ref_gene_name = sapply(strsplit(gsub("\\s+", "", ucsc_ref_gene_name), ";"), function(x) paste(unique(x), collapse = "; ")),
    ucsc_ref_gene_group = sapply(strsplit(gsub("\\s+", "", ucsc_ref_gene_group), ";"), function(x) paste(unique(x), collapse = "; "))
  ) |>
  filter(!is.na(p_value) & p_value != "",  !is.na(cor) & cor != "") 


|>
  filter(!is.na(ucsc_ref_gene_name) & ucsc_ref_gene_name != "") |>
  filter(cor < -0.75 | cor > 0.75, as.numeric(p_value) < 0.05) |>
  filter(str_detect(ucsc_ref_gene_group, "TSS"))
```

#export full results for supplement table
```{r}
write.table(cor_viz, "~/Documents/methyl_concor/result/methylation_suppl.txt", 
            sep = "\t", row.names = FALSE, quote = FALSE)
```


#formatting for summary table
```{r}
# Ensure the 'chr' variable is in the correct order
chr_levels <- paste0("chr", 1:22) # Add more levels if needed, e.g., for chrX, chrY
```


#summary table
```{r}
summary <- cor_viz |>
  filter(p_value < 0.05) |>
  mutate(p_value_group = ifelse(p_value < 0.05 , "< 0.05", "> 0.05"),
         cor_group = case_when(
           cor <= -0.8 ~ "<= -0.8",
           cor > -0.8 & cor <= -0.6 ~ "> -0.8 & <= -0.6",
           cor > -0.6 & cor <= -0.4 ~ "> -0.6 & <= -0.4",
           cor > -0.4 & cor <= -0.2 ~ "> -0.4 & <= -0.2",
           cor > -0.2 & cor < 0 ~ "> -0.2 & < 0",
           cor == 0 ~ "0",
           cor > 0 & cor <= 0.2 ~ "> 0 & <= 0.2",
           cor > 0.2 & cor <= 0.4 ~ "> 0.2 & <= 0.4",
           cor > 0.4 & cor <= 0.6 ~ "> 0.4 & <= 0.6",
           cor > 0.6 & cor <= 0.8 ~ "> 0.6 & <= 0.8",
           cor > 0.8 ~ "> 0.8"
         )) |>
  group_by(concord, p_value_group, cor_group, chr) |>
  summarise(
    count_cpg_sites = n(),
    count_genes = n_distinct(unlist(str_split(ucsc_ref_gene_name[ucsc_ref_gene_name != ""], ";"))),
    cross_listed_genes = sum(sapply(str_split(ucsc_ref_gene_name, ";"), function(x) length(unique(x)) > 1 && length(unique(x)) == length(x))),
    
    genes_list = paste(unique(ucsc_ref_gene_name[ucsc_ref_gene_name != ""]), collapse = ";"),
    count_Promotor = sum(str_detect(ucsc_ref_gene_group, "TSS")),
    count_Gene_Body = sum(str_detect(ucsc_ref_gene_group, "Body")),
    chr_cross_listed = paste0(unique(chr), " (", sapply(unique(chr), function(x) paste(
      c(
        if (sum(chr == x & str_detect(ucsc_ref_gene_group, "TSS")) > 0) paste0("TSS: ", sum(chr == x & str_detect(ucsc_ref_gene_group, "TSS"))),
        if (sum(chr == x & str_detect(ucsc_ref_gene_group, "Body")) > 0) paste0("Body: ", sum(chr == x & str_detect(ucsc_ref_gene_group, "Body"))),
        if (sum(chr == x & str_detect(ucsc_ref_gene_group, "3'UTR")) > 0) paste0("3UTR: ", sum(chr == x & str_detect(ucsc_ref_gene_group, "3'UTR"))),
        if (sum(chr == x & str_detect(ucsc_ref_gene_group, "5'UTR")) > 0) paste0("5UTR: ", sum(chr == x & str_detect(ucsc_ref_gene_group, "5'UTR")))
      ),
      collapse = ", "
    )), ")") %>% paste(collapse = "; "),
    
    
    cpg_cross_listed_regions = sum(str_detect(ucsc_ref_gene_group, "TSS") + str_detect(ucsc_ref_gene_group, "Body") + str_detect(ucsc_ref_gene_group, "3'UTR") + str_detect(ucsc_ref_gene_group, "5'UTR") > 1)
  )

write_csv(summary,
          file="~/Documents/methyl_concor/result/concordance_summary.csv")
```


#scatter plot
```{r}
ggplot(cor_viz,
       aes(x = p_value, y= cor))+
  geom_point()+
  theme_minimal()+
  facet_grid(~concord)
```

#correlation heatmap - subset
```{r}
ggplot(cor_viz, aes(x = factor(concord), 
                    y = cpg_site, fill = cor)) + #, label = value
  geom_tile(color = "white") +
  #geom_text(color = "black", size = 3, vjust = 1) +
  scale_fill_gradient2(low = "red", high = "royalblue", mid = "white",
                       midpoint = 0,
                       limit = c(-1, 1), space = "Lab",
                       name = "Spearman Correlation coefficient") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 11, hjust = 1),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom", legend.box = "horizontal") +
  facet_grid(.~chr)
```


#function for cross-listing issue
```{r}
extract_and_sum_after_colon <- function(text) {
  # Extract the part within parentheses
  within_parens <- str_extract(text, "\\((.*?)\\)")
  
  if (is.na(within_parens)) {
    return(NA_real_)
  }
  
  # Extract numeric values that follow ": "
  numbers <- str_extract_all(within_parens, "(?<=:\\s)\\d+")
  
  # Convert to numeric and sum
  numbers <- as.numeric(unlist(numbers))
  
  # Return the sum of numeric values
  return(sum(numbers, na.rm = TRUE))
}
```


#updated table for manuscript
```{r}
summary <- cor_viz |>
  filter(p_value < 0.05) |>
  mutate(p_value_group = ifelse(p_value < 0.05 , "< 0.05", "> 0.05"),
         cor_group = case_when(
           cor <= -0.8 ~ "<= -0.8",
           cor > -0.8 & cor <= -0.6 ~ "> -0.8 & <= -0.6",
           cor > -0.6 & cor <= -0.4 ~ "> -0.6 & <= -0.4",
           cor > -0.4 & cor <= -0.2 ~ "> -0.4 & <= -0.2",
           cor > -0.2 & cor < 0 ~ "> -0.2 & < 0",
           cor == 0 ~ "0",
           cor > 0 & cor <= 0.2 ~ "> 0 & <= 0.2",
           cor > 0.2 & cor <= 0.4 ~ "> 0.2 & <= 0.4",
           cor > 0.4 & cor <= 0.6 ~ "> 0.4 & <= 0.6",
           cor > 0.6 & cor <= 0.8 ~ "> 0.6 & <= 0.8",
           cor > 0.8 ~ "> 0.8"
         )) |>
  group_by(concord, p_value_group, cor_group, chr) |>
  summarise(
    count_cpg_sites = n(),
    count_genes = n_distinct(ucsc_ref_gene_name[ucsc_ref_gene_name != ""]),
    cross_listed_genes = sum(sapply(str_split(ucsc_ref_gene_name, ";"), function(x) length(unique(x)) > 1 && length(unique(x)) == length(x))),
    chr_cross_listed = paste0(
      unique(chr) %>% factor(levels = chr_levels) %>% sort() %>% as.character(),
      " (",
      sapply(unique(chr) %>% factor(levels = chr_levels) %>% sort() %>% as.character(), function(x) paste(
        c(
          if (sum(chr == x & str_detect(ucsc_ref_gene_group, "TSS")) > 0) paste0("TSS: ", sum(chr == x & str_detect(ucsc_ref_gene_group, "TSS"))),
          if (sum(chr == x & str_detect(ucsc_ref_gene_group, "Body")) > 0) paste0("Body: ", sum(chr == x & str_detect(ucsc_ref_gene_group, "Body"))),
          if (sum(chr == x & str_detect(ucsc_ref_gene_group, "3'UTR")) > 0) paste0("3UTR: ", sum(chr == x & str_detect(ucsc_ref_gene_group, "3'UTR"))),
          if (sum(chr == x & str_detect(ucsc_ref_gene_group, "5'UTR")) > 0) paste0("5UTR: ", sum(chr == x & str_detect(ucsc_ref_gene_group, "5'UTR"))),
          if (sum(chr == x & ucsc_ref_gene_group == "") > 0) paste0("NA: ", sum(chr == x & ucsc_ref_gene_group == ""))
        ),
        collapse = ", "
      )),
      ")"
    ) |>
      paste(collapse = "; "),
    cpg_cross_listed_regions = sum(str_detect(ucsc_ref_gene_group, "TSS") + str_detect(ucsc_ref_gene_group, "Body") + str_detect(ucsc_ref_gene_group, "3'UTR") + str_detect(ucsc_ref_gene_group, "5'UTR") > 1),
    numeric_sum = sapply(chr_cross_listed, extract_and_sum_after_colon)
  )

write_csv(summary,
          file="~/Documents/methyl_concor/result/concordance_summary_aug14.csv")
```

#manual check
```{r}
subset<- cor_viz |>
  filter(
    concord == "fp_mp",
    chr == "chr1",
    p_value < 0.05,
    cor >= 0.8
    #cor >= 0.6 & cor < 0.8
  )

#for manuscript text
result <- subset %>%
  separate_rows(ucsc_ref_gene_name, sep = ";") %>%
  mutate(ucsc_ref_gene_name = str_trim(ucsc_ref_gene_name)) %>%
  filter(ucsc_ref_gene_name != "") %>%
  count(ucsc_ref_gene_name) %>%
  summarise(
    unique_values = paste(ucsc_ref_gene_name, collapse = ", "),
    total_count = n()
  )

x<- summary |>
  filter(
    concord == "fp_mp",
    cor_group == "> 0.8"
  )
```


#summary for manuscript
```{r}
cor_viz<- readRDS("~/Documents/methyl_concor/result/methyl_conc_results.rds") |>
  mutate(
    ucsc_ref_gene_name = sapply(strsplit(gsub("\\s+", "", ucsc_ref_gene_name), ";"), function(x) paste(unique(x), collapse = "; ")),
    ucsc_ref_gene_group = sapply(strsplit(gsub("\\s+", "", ucsc_ref_gene_group), ";"), function(x) paste(unique(x), collapse = "; "))
  ) |>
  filter(!is.na(p_value) & p_value != "",  !is.na(cor) & cor != "")  |>
  filter(p_value < 0.05 & cor >0.5)

cpg_sites_all_levels <- cor_viz %>%
  group_by(cpg_site) %>%
  summarise(levels_present = n_distinct(concord)) %>%
  filter(levels_present == 3) %>%
  pull(cpg_site)

cpg_sites_list <- paste(cpg_sites_all_levels, collapse = ", ")
```

#manuscript last paragraph
```{r}
cor_viz<- readRDS("~/Documents/methyl_concor/result/methyl_conc_results.rds") |>
  mutate(
    ucsc_ref_gene_name = sapply(strsplit(gsub("\\s+", "", ucsc_ref_gene_name), ";"), function(x) paste(unique(x), collapse = "; ")),
    ucsc_ref_gene_group = sapply(strsplit(gsub("\\s+", "", ucsc_ref_gene_group), ";"), function(x) paste(unique(x), collapse = "; "))
  ) |>
  filter(!is.na(p_value) & p_value != "",  !is.na(cor) & cor != "")  |>
  filter(p_value < 0.05) |>
  select(c(1,2,4,5)) |>
  pivot_wider(
    names_from = concord,
    values_from = cor 
  )

x<- cor_viz |>
  filter(if_all(c(3,4), ~ . >= 0.85))

#print unique gene names with high correlation
print(paste(unique(na.omit(x$ucsc_ref_gene_name[x$ucsc_ref_gene_name != ""])), collapse = ", "))
```



#ternary plot for publication
```{r}
plot_df<- cor_viz |>
  select(c(1,2,4,5,8)) |>
  pivot_wider(names_from = concord, values_from = cor) |>
  rename(`CBMC-FP` = cbmc_fp,
         `CBMC-MP` = cbmc_mp,
         `FP-MP` = fp_mp)


ggtern(data= plot_df,
       aes(x=`CBMC-FP`, y=`CBMC-MP`, z=`FP-MP`))+
  geom_point(size=0.001, alpha = 1/15)+
  stat_density_tern(geom = "polygon", 
                    color = "white",
                    alpha = 0.001) +
  theme_rgbw()+
  labs(x = "CBMC-FP", y = "CBMC-MP", z = "FP-MP")

ggsave("~/Documents/methyl_concor/result/concor_plt.tiff",
       width = 7.5,height = 7.5,
       dpi=300
       )
```






